version: '3.9'

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - selenium
  selenium:
    image: selenium/standalone-chrome
    # ports:
    #   - 4444:4444
    # restart: always