version: "3.9"
services:
  app:
    build:
      context: .
    command: python3 ./seleniumDockerTest.py
    depends_on:
      - chrome

  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    shm_size: 2g