version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - selenium
  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
      - 7900:7900
    restart: always
  mysql:
    image: mysql:latest
    container_name: db_mysql
    ports:
      3306:3306
    environment:
      - MYSQL_DATABASE=mydev
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_USER=dbadmin
      - MYSQL_PASSWORD=12345678
      - TZ='Asia/Taiwan'
    volumes:
      - ./mysql/initdb:/docker-entrypoint-initdb.d # 啟動初期資料設定
      - ./mysql/datadir:/var/lib/mysql # 指定資料庫資料儲存位置
      - ./mysql/my.conf:/etc/mysql/conf.d/my.conf # mysql設定檔
    restart: always

    phpmyadmin:
      image: phpmyadmin:latest
      container_name: web_phpmyadmin
      ports:
        - 8080:80
      environment:
        # - PMA_ARBITRART = 1
        - PMA_HOST=mysql
        # - PMA_USER=root
        # - PMA_PASSWORD=12345678
      links:
        - mysql
      restart: always