version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - selenium
  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
      - 7900:7900
    restart: always