version: '3.9'

services:
  selenium:
    image: selenium/standalone-chrome
    shm_size: 2g
    ports:
      - 4444:4444
    restart: always
  
  app:
    build:
      context: .
    volumes:
      - .:/app
    command: sh -c "python3 seleniumDockerTest.py"
    depends_on:
      - selenium